# Generated by Django 5.2.1 on 2025-05-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscard',
            name='description',
        ),
        migrations.RemoveField(
            model_name='businesscard',
            name='image',
        ),
        migrations.RemoveField(
            model_name='businesscard',
            name='title',
        ),
        migrations.AddField(
            model_name='businesscard',
            name='back_image',
            field=models.ImageField(default='', upload_to='cards/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesscard',
            name='front_image',
            field=models.ImageField(default=1, upload_to='cards/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
